# Generated by Django 4.0.4 on 2022-04-27 18:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('rock_type', models.CharField(choices=[('Conglomerate', 'Conglomerate'), ('Gneiss', 'Gneiss'), ('Granite', 'Granite'), ('Limestone', 'Limestone'), ('Sandstone', 'Sandstone'), ('Other', 'Other')], max_length=12)),
                ('climbing_type', models.CharField(choices=[('Bouldering', 'Bouldering'), ('Ice Climbing', 'Ice Climbing'), ('Sport Climbing', 'Sport Climbing'), ('Trad Climbing', 'Trad Climbing'), ('Other', 'Other')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='ClimbingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application_deadline_date', models.DateField()),
                ('trip_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trip_description', models.TextField()),
                ('trip_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('trip_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climbing_guide.climbinglocation')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_guide.climbingtrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
