# Generated by Django 4.0.4 on 2022-04-29 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingtripapplication',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='climbingtripapplication',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='climbingtrip',
            name='trip_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
